name: Run Gradle on PRs
on:
  pull_request:
  push:
      branches: [main, test_branch]
jobs:
    integrationJavaTests:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest]
                version: [17, 19]
                vendor: [temurin, zulu, liberica]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Execute Gradle build
              run: |
                  ./gradlew :help
                  where jstat
                  jps | grep GradleDaemon | sed 's/GradleDaemon//' | while read ln; do  jstat -gc -t $ln; echo "$ln"; done
